import pandas as pd
import numpy as np
from Stock_MST_Classes import (
    StockInfo,
    stockMST,
    Optimizer,
    Backtester
)
import datetime
import math
import pytest

'''
Quotation: 
test cases generated by AI, 
I input the prompt for what cases I want it to test,
double-checked, customized the inputs and adjusted based on generated cases.

Notes:
The warning messages generated during the tests are due to api settings.
Since we hardcoded the price df in the test file, there is no api call,
and the warning is due to api error handler. Not related to the features themselves.
'''

#==================1. Test StockInfo correlation → distance (no Yahoo call)===========
# inject a fake price_df directly so nothing is downloaded.
def test_stockinfo_corr_to_distance_local():
    # Create a tiny synthetic price DataFrame
    dates = pd.date_range("2020-01-01", periods=5, freq="D")
    prices = pd.DataFrame(
        {
            "AAA": [100, 101, 102, 103, 104],
            "BBB": [50, 50.5, 51, 51.5, 52],  # almost perfectly correlated with AAA
            "CCC": [10, 9, 11, 8, 12],        # more noisy
        },
        index=dates,
    )

    si = StockInfo(["AAA", "BBB", "CCC"], "2020-01-01", "2020-01-10")
    si.price_df = prices  # bypass yfinance

    corr = si.getCorrMatrix()
    dist_df = si.CorrToDistance()

    # Correlation diagonal = 1 → distance 0
    for t in ["AAA", "BBB", "CCC"]:
        assert math.isclose(dist_df.loc[t, t], 0.0)

    # Higher correlation → smaller distance
    rho_AB = corr.loc["AAA", "BBB"]
    rho_AC = corr.loc["AAA", "CCC"]
    assert abs(rho_AB) > abs(rho_AC)  # AB is more correlated than AC

    d_AB = dist_df.loc["AAA", "BBB"]
    d_AC = dist_df.loc["AAA", "CCC"]
    assert d_AB < d_AC

#==================2. Test stockMST.generateMST on a simple triangle===========
def test_stockmst_generateMST_triangle():
    # Distances: AB=1, BC=2, AC=10 → MST should keep AB and BC (total=3)
    tickers = ["A", "B", "C"]
    dist = pd.DataFrame(
        [
            [0.0, 1.0, 10.0],
            [1.0, 0.0, 2.0],
            [10.0, 2.0, 0.0],
        ],
        index=tickers,
        columns=tickers,
    )

    mst_obj = stockMST(dist)
    min_weight, mst = mst_obj.minweight, mst_obj.mst

    # Check total MST weight
    assert math.isclose(min_weight, 1.0 + 2.0)

    # Graph should have undirected edges AB and BC
    assert set(mst.keys()) == {"A", "B", "C"}
    assert mst["A"] == {"B": 1.0}
    assert mst["B"]["A"] == 1.0
    assert mst["B"]["C"] == 2.0
    assert mst["C"]["B"] == 2.0

#==================3. Test generateRootedTree, computeDegrees, computeSubtreeSize===========
#Use a simple star MST centered at "O".
def build_star_mst():
    # O is center, three leaves with weights 1,2,3
    mst = {
        "O": {"A": 1.0, "B": 2.0, "C": 3.0},
        "A": {"O": 1.0},
        "B": {"O": 2.0},
        "C": {"O": 3.0},
    }
    return mst

def test_rooted_tree_and_subtrees():
    mst_obj = stockMST.__new__(stockMST)  # bypass __init__
    mst_obj.mst = build_star_mst()

    parent, children, dist_to_parent, distance, depth = mst_obj.generateRootedTree("O")

    # Parent checks
    assert parent["O"] is None
    assert parent["A"] == "O"
    assert parent["B"] == "O"
    assert parent["C"] == "O"

    # Children checks
    assert set(children["O"]) == {"A", "B", "C"}
    assert children["A"] == []
    assert children["B"] == []
    assert children["C"] == []

    # Distances from root O
    assert distance["O"] == 0.0
    assert distance["A"] == 1.0
    assert distance["B"] == 2.0
    assert distance["C"] == 3.0

    # Depth
    assert depth["O"] == 0
    assert depth["A"] == 1
    assert depth["B"] == 1
    assert depth["C"] == 1

    # Degrees
    degrees = mst_obj.computeDegrees()
    assert degrees["O"] == 3
    assert degrees["A"] == 1
    assert degrees["B"] == 1
    assert degrees["C"] == 1

    # Subtree sizes (root at O)
    subtree_sizes = mst_obj.computeSubtreeSize("O", parent)
    assert subtree_sizes["O"] == 4
    assert subtree_sizes["A"] == 1
    assert subtree_sizes["B"] == 1
    assert subtree_sizes["C"] == 1

#==================4.Test getKnearestneihgbor on the star==================
def test_k_nearest_neighbor():
    mst_obj = stockMST.__new__(stockMST)
    mst_obj.mst = build_star_mst()

    # From center O, nearest 2 neighbors should be A (1.0), B (2.0)
    res = mst_obj.getKnearestneihgbor("O", K=2)
    # res is [[dist, node], ...] sorted ascending
    assert len(res) == 2
    assert res[0][1] == "A"
    assert res[1][1] == "B"

#==================5.Test Optimizer (DP + backtracking) on a small chain===========
#build a tiny line A–B–C and compare to hand-calculated optimal subsets
def build_chain_mst():
    # A - B - C with weights 1, 2
    mst = {
        "A": {"B": 1.0},
        "B": {"A": 1.0, "C": 2.0},
        "C": {"B": 2.0},
    }
    return mst

def test_optimizer_chain_K2_K3():
    # Build distance matrix consistent with MST
    # Distances along tree:
    # AB=1, BC=2, AC=3
    tickers = ["A", "B", "C"]
    dist_matrix = {
        "A": {"A": 0.0, "B": 1.0, "C": 3.0},
        "B": {"A": 1.0, "B": 0.0, "C": 2.0},
        "C": {"A": 3.0, "B": 2.0, "C": 0.0},
    }

    # Attach MST to stockMST instance
    mst_obj = stockMST.__new__(stockMST)
    mst_obj.mst = build_chain_mst()

    # Root at B for symmetry
    parent, children, dist_to_parent, distance, depth = mst_obj.generateRootedTree("B")

    # Optimizer works on rooted tree
    opt = Optimizer(parent, children, dist_to_parent, root="B")

    # ----- K = 2 -----
    K = 2
    result2 = opt.GetminCorrPortfolio(K)
    value2 = result2["maximum pairwise distance sum"]
    selected2 = result2["selected K tickers"]
    assert len(selected2) == 2

    # Best pair by hand is (A, C) with distance 3.0
    assert math.isclose(value2, 3.0)
    assert set(selected2) == {"A", "C"}

    # ----- K = 3 -----
    K = 3
    result3 = opt.GetminCorrPortfolio(K)
    value3 = result3["maximum pairwise distance sum"]
    selected3 = result3["selected K tickers"]
    assert set(selected3) == {"A", "B", "C"}

    # total pairwise = AB + BC + AC = 1 + 2 + 3 = 6
    assert math.isclose(value3, 6.0)

#==================6. Test Optimizer.backtrackingSelection consistency==================
#check that the backtracked selection matches DP value for another small tree (star).
def compute_pairwise_sum_from_dist_matrix(selected, dist_matrix):
    sel = list(selected)
    total = 0.0
    for i in range(len(sel)):
        for j in range(i+1, len(sel)):
            u, v = sel[i], sel[j]
            total += dist_matrix[u][v]
    return total

def test_optimizer_star_backtracking():
    mst_obj = stockMST.__new__(stockMST)
    mst_obj.mst = build_star_mst()

    parent, children, dist_to_parent, distance, depth = mst_obj.generateRootedTree("O")
    opt = Optimizer(parent, children, dist_to_parent, root="O")

    # dist matrix consistent with star:
    # O-A=1, O-B=2, O-C=3
    # leaf-leaf distances are sums via O
    dist_matrix = {
        "O": {"O": 0, "A": 1, "B": 2, "C": 3},
        "A": {"O": 1, "A": 0, "B": 3, "C": 4},
        "B": {"O": 2, "A": 3, "B": 0, "C": 5},
        "C": {"O": 3, "A": 4, "B": 5, "C": 0},
    }

    K = 3
    res = opt.GetminCorrPortfolio(K)
    value = res["maximum pairwise distance sum"]
    selected = res["selected K tickers"]

    assert len(selected) == 3
    brute = compute_pairwise_sum_from_dist_matrix(selected, dist_matrix)
    # DP value should match true pairwise sum
    assert math.isclose(value, brute)

#==================Call the functions==================
test_stockinfo_corr_to_distance_local()
test_stockmst_generateMST_triangle()
build_star_mst()
test_k_nearest_neighbor()
test_optimizer_chain_K2_K3()
test_optimizer_star_backtracking()